/* Autogenerated by /usr/bin/comp on Tue Jun 25 20:28:38 2013 -- do not edit */
#include "rtapi.h"
#ifdef RTAPI
#include "rtapi_app.h"
#endif
#include "rtapi_string.h"
#include "rtapi_errno.h"
#include "hal.h"

static int comp_id;

#ifdef MODULE_INFO
MODULE_INFO(linuxcnc, "component:LTC1286:This component converts a twelve bit serial word from an LTC1286 ADC into an unsigned word.(2008/01/22 kwallace@wallacecompany.com)");
MODULE_INFO(linuxcnc, "pin:bit_in:bit:0:in:This is the value of the n'th bit from the ADC data line.:None:None");
MODULE_INFO(linuxcnc, "pin:clock_out:bit:0:out:This commands (on the falling edge) the ADC to clock the n'th bit onto the data line.:None:None");
MODULE_INFO(linuxcnc, "pin:cs_out:bit:0:out:This commands (on the falling edge) the ADC to get ready to convert the analog input to serial binary.:None:None");
MODULE_INFO(linuxcnc, "pin:byte_out:u32:0:out:This is the byte value of the analog signal with full scale at 4095 at 5 Volts.:None:None");
MODULE_INFO(linuxcnc, "funct:_:0:");
MODULE_INFO(linuxcnc, "license:GPL");
MODULE_LICENSE("GPL");
#endif // MODULE_INFO


struct __comp_state {
    struct __comp_state *_next;
    hal_bit_t *bit_in;
    hal_bit_t *clock_out;
    hal_bit_t *cs_out;
    hal_u32_t *byte_out;
    unsigned which_bit;

    unsigned accum;

    unsigned adc_mode;

    unsigned adc_step;

};
struct __comp_state *__comp_inst=0;
struct __comp_state *__comp_first_inst=0, *__comp_last_inst=0;

static void _(struct __comp_state *__comp_inst, long period);
static int __comp_get_data_size(void);
#undef TRUE
#define TRUE (1)
#undef FALSE
#define FALSE (0)
#undef true
#define true (1)
#undef false
#define false (0)

static int export(char *prefix, long extra_arg) {
    char buf[HAL_NAME_LEN + 1];
    int r = 0;
    int sz = sizeof(struct __comp_state) + __comp_get_data_size();
    struct __comp_state *inst = hal_malloc(sz);
    memset(inst, 0, sz);
    r = hal_pin_bit_newf(HAL_IN, &(inst->bit_in), comp_id,
        "%s.bit-in", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_OUT, &(inst->clock_out), comp_id,
        "%s.clock-out", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_OUT, &(inst->cs_out), comp_id,
        "%s.cs-out", prefix);
    if(r != 0) return r;
    r = hal_pin_u32_newf(HAL_OUT, &(inst->byte_out), comp_id,
        "%s.byte-out", prefix);
    if(r != 0) return r;
    inst->which_bit = 11.0;
    rtapi_snprintf(buf, sizeof(buf), "%s", prefix);
    r = hal_export_funct(buf, (void(*)(void *inst, long))_, inst, 0, 0, comp_id);
    if(r != 0) return r;
    if(__comp_last_inst) __comp_last_inst->_next = inst;
    __comp_last_inst = inst;
    if(!__comp_first_inst) __comp_first_inst = inst;
    return 0;
}
static int default_count=1, count=0;
char *names[16] = {0,};
RTAPI_MP_INT(count, "number of LTC1286");
RTAPI_MP_ARRAY_STRING(names, 16, "names of LTC1286");
int rtapi_app_main(void) {
    int r = 0;
    int i;
    comp_id = hal_init("LTC1286");
    if(comp_id < 0) return comp_id;
    if(count && names[0]) {
        rtapi_print_msg(RTAPI_MSG_ERR,"count= and names= are mutually exclusive\n");
        return -EINVAL;
    }
    if(!count && !names[0]) count = default_count;
    if(count) {
        for(i=0; i<count; i++) {
            char buf[HAL_NAME_LEN + 1];
            rtapi_snprintf(buf, sizeof(buf), "LTC1286.%d", i);
        r = export(buf, i);
            if(r != 0) break;
       }
    } else {
        for(i=0; names[i]; i++) {
        r = export(names[i], i);
            if(r != 0) break;
       }
    }
    if(r) {
        hal_exit(comp_id);
    } else {
        hal_ready(comp_id);
    }
    return r;
}

void rtapi_app_exit(void) {
    hal_exit(comp_id);
}

#undef FUNCTION
#define FUNCTION(name) static void name(struct __comp_state *__comp_inst, long period)
#undef EXTRA_SETUP
#define EXTRA_SETUP() static int extra_setup(struct __comp_state *__comp_inst, char *prefix, long extra_arg)
#undef EXTRA_CLEANUP
#define EXTRA_CLEANUP() static void extra_cleanup(void)
#undef fperiod
#define fperiod (period * 1e-9)
#undef bit_in
#define bit_in (0+*__comp_inst->bit_in)
#undef clock_out
#define clock_out (*__comp_inst->clock_out)
#undef cs_out
#define cs_out (*__comp_inst->cs_out)
#undef byte_out
#define byte_out (*__comp_inst->byte_out)
#undef which_bit
#define which_bit (__comp_inst->which_bit)
#undef accum
#define accum (__comp_inst->accum)
#undef adc_mode
#define adc_mode (__comp_inst->adc_mode)
#undef adc_step
#define adc_step (__comp_inst->adc_step)


#line 19 "LTC1286.comp"

FUNCTION(_) {
    switch (adc_mode) {
        case 0:                                       // ***  Mode 0 : Wake-up
            cs_out=0;                                 // Set cs_out low to wake up the ADC
            clock_out=0x1 & adc_step;                 // Set clock_out high on odd adc_step's
            if (adc_step>=6) { adc_mode=1; }          // If step 6 is the end of wake-up, so change to next mode
            adc_step++;
            break;
        case 1:                                       // ***  Mode 1 : Shift Data from ADC
            clock_out=0x1 & adc_step;                 // Set clock_out high on odd adc_step's
            if (clock_out) {                          // If clock_out is high ...
                if (bit_in) {                         // check if bit is high, if so ...
                    accum = accum | (1 << which_bit); // shift to current bit location, and add to accumulator.
                }
                which_bit--;
            }
            if (adc_step>=29) {                       // If we are at step 29, we are done data shifting, so ...
                adc_mode=2;                           // change to the next mode,
                which_bit=11;                         // reset the bit counter,
                byte_out=accum;                       // output the finished byte,
                accum=0;                              // reset the accumulator.
            }
            adc_step++;
            break;
        case 2:                                       // ***  Mode 2 : Invoke Sleep
            cs_out=1;                                 // Set cs_out high to put the ADC to sleep
            if (adc_step>=31) {                       // If we are at step 31, we are done, so ...
                adc_mode=0;                           // get ready to start again.
                adc_step=0;
            } else { adc_step++; }
            break;
    }
}

static int __comp_get_data_size(void) { return 0; }
