.TH OR4 "9" "2012-10-05" "LinuxCNC Documentation" "HAL Component"
.de TQ
.br
.ns
.TP \\$1
..

.SH NAME

or4 \- ored 4 inputs
.SH SYNOPSIS
.HP
.B loadrt or4 [count=\fIN\fB|names=\fIname1\fB[,\fIname2...\fB]]
.SH FUNCTIONS
.TP
\fBor4.\fIN\fB\fR (requires a floating-point thread)

.SH PINS
.TP
.B or4.\fIN\fB.in0\fR bit in \fR
.TQ
.B or4.\fIN\fB.in1\fR bit in \fR
.TQ
.B or4.\fIN\fB.in2\fR bit in \fR
.TQ
.B or4.\fIN\fB.in3\fR bit in \fR
.TQ
.B or4.\fIN\fB.out\fR bit out \fR
.SH LICENSE

GPL
